name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo usermod -aG docker $USER
        sudo chmod 666 /var/run/docker.sock

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set PYTHONPATH to include src/
      run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

    - name: Verify Docker installation
      run: docker --version

    - name: Run tests with pytest
      run: pytest tests/
