name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Install Docker using Docker's official script
    - name: Install Docker
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo usermod -aG docker $USER
        sudo systemctl start docker
        sudo chmod 666 /var/run/docker.sock

    # Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Set PYTHONPATH to include src/
    - name: Set PYTHONPATH to include src/
      run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

    # Verify Docker installation
    - name: Verify Docker installation
      run: docker --version
